---
title: "Design and Analysis of Two-Phase Studies"
author: "Thomas Lumley"
format: 
  revealjs:
      slide-number: true
---

## Outline

### Day 1, Session 1

-	Introduction to two-phase sampling
-	Survey package 
-	Raking of weights


### Day 1, Session 2

-	Fitting regression models in two-phase data
-	Influence functions and imputation for raking
- Connections to AIPW estimation

---

### Day 2, Session 1

- Optimal sampling for two-phase designs
- Neyman allocation and influence functions
- Strata vs individual probabilities
- Multiparameter optimisation

### Day 2, Session 2

- Multiwave designs
- Analysis approaches beyond weighting
- Discussion and wrap-up

---

### Session structure

First three sessions:

- 45 min lecture
- 30 min exercise 
- 15 min discussion.

(no exercises in last session)

---

## Introduction

Me: 

- theoretical biostatistician based in Auckland, New Zealand
- part of Bryan Shepherd/Pamela Shaw research group 
- sings baritone


You?

# Two-phase sampling

In which we do one thing after another


## Two-**phase** sampling

- Phase 1: take a sample of $N$ ($\pi_{1,i}$) 
    - (or pretend your cohort/database is a sample)

- Phase 2: take a subsample of $n$ ($\pi_{2|1,i}$) 
    - phase-2 sampling probabilities can depend on any phase-1 data

Weight using reciprocal of $\pi^*_i=\pi_{1,i}\pi_{2|1,i}$

**Q:** Why is this **not** the probability $i$ is in the subsample?


---

## Nested case-control

Binary outcome $Y$ measured on whole cohort

Stratified sampling: all cases, same number of controls

Measure exposure $X$ on cases, controls

## Case-cohort

Sample $m$ people from cohort and measure $X$

Also measure $X$ on everyone who has an event

## Measurement-error

Measure $Y$ and error-prone variable $A$ on whole cohort

- subsample same number from each cell of $A\times Y$
- measure true $X$ on subsample

## EHR data

Measure $Y$ and *many* $Z$, $A$ on whole cohort

- subsample small number of people to validate against clinical notes
- measure many $X$ on subsample


## General case

- Want to fit $Y\sim X+Z$
- Measure $Z$, $A$, perhaps $Y$ on everyone
- Measure $X$ on the subsample
- $R$ is subsampling indicator

Sometimes $A$ predicts $X$ well, sometimes not

Sometimes $Z,A$ is high-dimensional, sometimes not

Sometimes $X$ is high-dimensional, sometimes not

*We will usually take $\pi_{i,1}$ to be constant: iid sample at phase 1*

# Inference and computation


## Weighting

$w_i=1/{\pi^*_i}$ or $1/\pi_{2|1,i}$ are *design* or *grossing-up weights*

Person $i$ in the subsample **represents** $w_i$ people in the population/cohort.

$$E[\color{red}{w_iR_i}]=E\left[\frac{R_i}{\pi_i^*}\right]=1$$
**We can put $\color{red}{w_iR_i}$ into any sum over $i=1,\dots,N$ to get a weighted sample version**

Unlike most surveys, we (typically) don't have non-response



## Two levels of randomness

Cohort was random: we would have (?model) uncertainty even with complete data

Subsample is random: we have pure sampling uncertainty

## Totals

Whole-cohort total (*census parameter*): 
$\tilde{T}_X=\sum_{i=1}^N X_i$

Estimator: $\hat T_X=\sum_{i=1}^N \color{red}{w_iR_i} X_i$

$$\mathrm{var}[\hat T_X]= \mathrm{var}[E[\hat T_X|\text{phase 1}]]+E[\mathrm{var}[\hat T_X|\text{phase 1}]]$$
First term is full-cohort $\mathrm{var}[\tilde T_X]$, second is sampling variance

## Using the whole cohort

We have $Y, Z, A$ on $N-n$ unsampled people. 

Define raking variables $H_i=H(Y,Z,A)$ and compute raking adjustments $g_i$ so that

$$\sum_{i=1}^N \color{blue}{g_iw_iR_i}H_i=\sum_{i=1}^N H_i$$

- There is *no* subsampling error in $\sum_{i=1}^N \color{blue}{g_iw_iR_i}H_i$
- There is *reduced* subsampling error for anything correlated with $H_i$

---

### Impact

Before raking

$$\text{var}[\hat T_X]=\sum_{i,j=1}^n w_iX_i\,w_jX_j\,\text{cov}[R_i,R_j]$$

After raking 

$$\mathrm{var}[\hat T_X]=\sum_{i,j=1}^n w_ie_i\,w_je_j\,\mathrm{cov}[R_i,R_j]$$

where $e_j$ are **residuals** from regressing $X$ on $H$

---

## Computation

```
library(survey)
cc_design<-twophase(id=list(~1,~1), 
    strata=list(NULL, ~y), 
    subset=~in_sample,
    data=data)
```



# Exercises

# Discussion

# Break

Coffee?

# Regression models

In which a line must be drawn

## Questions

- how do we do weighted estimation?
- how do we estimate uncertainty?
- what are good raking variables?
- isn't it horribly inefficient?
- why isn't it all well known?

---

### Subsampled history of weighted estimation

- Neyman (1938): 'double sampling'
- White (1982): two-phase sampling in epi
- Valliant (1993): variance estimation after post-stratification
- Binder (1983, 1996): estimating equations
- Deville, Särndal (1992, 1993): arbitrary raking variables
- Robins, Rotnitzky, Zhao (1994): AIPW, efficiency
- Breslow et al (2009): "Using the whole cohort..." 
- Lumley, Shaw, Dai (2010): Connecting the literature
- Lumley: `survey` package implementations


## Fitting models in two-phase samples

Again: $(Y,Z,A)\mid (R,X)$

For point estimates we can just put $w_i$ in the objective function

$\tilde\ell(\theta)=\sum_{i=1}^N \ell_i(\theta)$ 

giving the census parameter $\tilde\theta$, goes to

$\hat\ell (\theta)=\sum_{i=1}^N \color{red}{w_iR_i}\ell_i(\theta)$ 

giving the weighted estimator $\hat\theta$

## Influence functions

Suppose we can write in iid data
$$\sqrt{N}(\tilde\theta-\theta)=\frac{1}{\sqrt{n}}\sum_{i=1}^N h(X_i,Y_i,Z_i;\theta)+o_p(1)$$

$h_i=(X_i,Y_i,Z_i;\theta)$ are **influence functions**

Influence functions turn any statistic into a sum!

---

### Examples

- Regression: $h_i=n(X^TX)^{-1}x_i(y_i-x_i'\beta)$


- If $\hat\theta$ solves $U(\theta)=\sum_i U_i(\theta)=0$ then 
$$h_i=E\left[\frac{1}{n}\frac{\partial U}{\partial\theta}\right]^{-1}U_i(\theta)$$


## Influence functions!

- variance of $\hat\theta$ is variance of $\sum_i\color{red}{w_iR_i}h_i$
- variance after raking projects $h_i$ orthogonal to $H_i$
- good raking variables $H_i$ are correlated with $h_i$
- optimal design for $\sum_i h_i$ is optimal for $\hat\theta$

Everything looks like a sum!

$\scriptsize \text{(not lasso, quantiles, mixed models)}$


# Bye for now

Same time tomorrow


# Optimal design

In which some have more chance than others

# But first!

**Questions**?

## Optimal design

Suppose we are given an population divided into $K$ strata, and one variable

- Stratum $k$ has $N_k$ people in the population
- a variable $Y$ has variance $\sigma^2_k$ in stratum $k$

Want to estimate the population total (or mean) of $Y$

$$\mathrm{var}[\hat T_Y]= \sum_k N_k^2\sigma^2_k/n_k$$
given $\sum_k n_k=\text{allowed }n$

## Solution

- Continuous approximation (Neyman, 1934): $n_k\propto N_k\sigma_k$
- Straightforward exact algorithm (Wright, 2017)

Optimal stratum choice is harder, but  we know

- stratum all the same size
- stratum size=2 is ideal
- (post-stratification needs larger strata)


## Regression models

How do we translate this result to optimal design for estimating a $\beta$? 🤔


## Regression models

How do we translate this result to optimal design for estimating a $\beta$? 


**Influence functions!!**

$$n_k\propto N_k\sigma_k$$

where $\sigma^2_k$ is now the variance of the efficient influence function for $\beta$ in the complete cohort



# Exercises

# Discussion

# Break

Coffee?

# Maximum likelihood

In which models are the evidence of things  not seen

## Agenda

We have not been assuming the outcome model $Y|X,Z$ is correctly specified

The *semiparametric information bound* is much worse if you don't assume $Y|X,Z$ is correct

Now we will look at semiparametric likelihood analyses 

- The Auckland school: NPMLE for discrete phase-1 data (`missreg3`)
- Tao, Lin, Lotspeich *et al*: NPMLE for continuous phase-1 data and arbitrary measurement error (`sleev`)

# General principles

## Analysis

Model assisted:

- inference is valid for misspecified models
- correct models give more efficient results
- nearly-correct models are almost as good


Model assisted:

- correct models give large efficiency gains over weighting
- inference is invalid for misspecified models
- nearly-correct models can be seriously inferior


## Design

Model assisted

- anything could happen where we don't look
- need to sample everywhere ($\pi>0$)
- design is robust to small model changes

Model-based

- the model tells us what is happening everywhere
- some zero sampling probabilities may be optimal
- design is sensitive to small model changes


## Case-control logistic regression

- Model-assisted: weighted logistic regression (`svyglm`)
- Model-based: unweighted logistic regression (`glm`) is MLE (Prentice & Pyke) and is fully efficient (Breslow, Robins, Wellner)

Large effiency gains with model-based estimation, but mostly for strong effects of continuous covariates. Gain is sensitive to model correctness.

Optimal design is roughly the same for both 

## Generalising case-control

Chris Wild & Alastair Scott (*et al*)

Given a model for $Y|X,Z$ and a sampling rule for $R|Y,Z,A$ we can derive sampling weights from the model and the population distribution of $Y,Z,A$ 

Need discrete strata $S=Y\times A$ but not discrete $X,Z$

Using these weights instead of design weights or post-stratification weights gives maximum likelihood estimates. (needs iterative maximisation)

##  Eg

`missreg`

## Extensions

- $Y$ can be continuous: need to make finite set of bins for strata
- logistic mixed models: genetics, longitudinal

## Limitations

Phase 1 data 

- are only used as sampling strata
- must be discrete, low-dimensional
- Strata must be perfect surrogates: $[Y|Z,X,S]=[Y|Z,X]$


## Misspecification

The benefit of MLE over raking is $O(n^{-1/2})$ when the model is correct, so we must also care about $O(n^{-1/2})$ biases from misspecification.

These are misspecifications that are not reliably detectable: an omitted variable with $\delta/\sqrt{n}$ coefficient can be detected asymptotically with power $<1$ depending on $\delta$.

Han *et al* (2021) confirmed that worst-case directions of misspecification will make the MLE less accurate than weighted estimation (for estimating the full-cohort best-fitting model.)

---

[picture]

---

Take-home message

- MLE can sometimes provide large precision gains
- Gains are sensitive to *exact* model specification (untestably good)
- *you pays your money and you take your choice*

## Continuous phase 1

- [Y|X,Z] correctly specified
- $X$ with measurement error is an $A$
- $Y$ with measurement error is an $A$
- measurement error distribution is nonparametric
- phase 1 has to be low dimensional (eg, two-d)

Idea: 'sieve' estimation, *ie*, parametric models getting more complicated with $n$. Specifically, $B$-splines. 

## Sieve estimation

`sleev`

